image: node:20

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    GITLAB_PAGES: "true"
  script:
    - npm ci
    - GITLAB_PAGES=true npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main
